CREATE OR REPLACE FUNCTION layer_highway_area(bbox GEOMETRY, zoom_level INT)
RETURNS TABLE(
    osm_id BIGINT,
    way GEOMETRY,
    highway TEXT,
    layer INT,
    type TEXT,
    footway TEXT,
    cycleway TEXT,
    service TEXT,
    tracktype TEXT,
    bridge TEXT,
    tunnel TEXT,
    grade INT,
    smoothness INT,
    surface TEXT,
    "mtb:scale" TEXT,
    sac_scale TEXT,
    attribution TEXT,
    lanes TEXT,
    lit TEXT,
    sidewalk TEXT,
    width TEXT,
    maxspeed TEXT,
    is_link BOOLEAN,
    is_bridge BOOLEAN,
    is_tunnel BOOLEAN,
    junction TEXT,
    is_construction BOOLEAN,
    is_proposed BOOLEAN
    ref TEXT,
    int_ref TEXT,
    ref_length INT,
    intref_length INT,
    oneway INT,
    has_name BOOLEAN,
    name TEXT,
    way_length REAL,
    access TEXT,
    foot TEXT,
    ski TEXT,
    "ski:nordic" TEXT,
    "ski:alpine" TEXT,
    "ski:telemark" TEXT,
    inline_skates TEXT,
    ice_skates TEXT,
    horse TEXT,
    vehicle TEXT,
    bicycle TEXT,
    carriage TEXT,
    trailer TEXT,
    caravan TEXT,
    motor_vehicle TEXT,
    motorcycle TEXT,
    moped TEXT,
    mofa TEXT,
    motorcar TEXT,
    motorhome TEXT,
    psv TEXT,
    bus TEXT,
    atv TEXT,
    taxi TEXT,
    tourist_bu TEXT,s
    goods TEXT,
    hgv TEXT,
    agricultural TEXT,
    ATV TEXT,
    snowmobile TEXT
) AS $$
    SELECT
        osm_id, way, get_highway(highway, constructino, proposed) as highway, get_layer(layer, is_bridge, is_tunnel),
		get_highway_type(get_highway(highway, construction, proposed), tracktype, surface, smoothness) AS type,
	    footway, cycleway, service, tracktype, bridge, tunnel,
        get_highway_grade(get_highway(highway, construction, proposed), tracktype) AS grade,
        get_smoothness(smoothness::INT, highway, tracktype, surface) AS smoothness,
	    surface, "mtb:scale", sac_scale, attribution, lanes, lit, sidewalk, width, maxspeed,
	    get_highway(highway, construction, proposed) in
	        ('motorway_link','trunk_link','primary_link','secondary_link','tertiary_link') AS is_link,
	    is_bridge, is_tunnel, COALESCE(junction,CAST('no' AS text)) AS junction,
		get_is_construction(highway, construction) AS is_construction,
		get_is_proposed(highway, proposed) AS is_proposed,
	    ref, int_ref, LENGTH(ref) AS ref_length, LENGTH(int_ref) AS intref_length, oneway,
		(name IS NOT NULL AND name <> '') AS has_name, name, ST_Length(ST_Transform(way,900913)) AS way_length,
	    access,foot,ski,"ski:nordic","ski:alpine","ski:telemark",ice_skates,inline_skates,horse,
	    vehicle,bicycle,carriage,trailer,caravan,motor_vehicle,motorcycle,moped,mofa,motorcar,motorhome,
	    psv,bus,taxi,tourist_bus,goods,hgv,agricultural,ATV,snowmobile
	FROM highway_area
    WHERE way && bbox
    ORDER BY way_area DESC

$$ LANGUAGE SQL IMMUTABLE;